services:
  database:
    image: postgres:16
    container_name: arquila-postgres
    environment:
      POSTGRES_DB: arquila
      POSTGRES_USER: arquila
      POSTGRES_PASSWORD: arquila
    ports:
      - "5432:5432"
    volumes:
      - arquila_pgdata:/var/lib/postgresql/data

volumes:
  arquila_pgdata:
